FROM node:20.5.0-alpine3.17

# outputs python installation logs straight into terminal to trace in docker
ENV PYTHONUNBUFFERED=1

# install dependencies for node-gyp 
# because @nx/workspace uses @parcel/watcher that uses parcel that uses node-gyp
# https://github.com/nodejs/node-gyp#on-unix
RUN apk add --update --no-cache python3 make g++ zsh

WORKDIR /app

RUN npm install -g pnpm

COPY . .

RUN pnpm config set store-dir ./.pnpm-store
# maybe useful for build image, not sure about dev image
# RUN pnpm install --frozen-lockfile
RUN pnpm install
