version: "3.9"

volumes:
  node_modules:
  pnpm-store:

services:
  plgrnd:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: "plgrnd"
    container_name: "plgrnd-dev-container"
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - pnpm-store:/app/.pnpm-store
    command: sleep infinite

  # example-webpack-app:
  #   image: "plgrnd"
  #   container_name: "example-webpack-app"
  #   ports:
  #     - 3001:3000
  #   command: ["pnpm", "nx", "run", "example-webpack-app:serve-bundle"]
